name: C/C++ CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [normal, thread, address]
    outputs:
      matrix_type: ${{ matrix.type }}
    steps:
      - uses: actions/checkout@v4

      - name: Build & Run ${{ matrix.type }} test
        run: |
          make fclean
          if [ "${{ matrix.type }}" = "normal" ]; then
            sudo make test
          elif [ "${{ matrix.type }}" = "thread" ]; then
            sudo make debug_test
          elif [ "${{ matrix.type }}" = "address" ]; then
            sudo _ADDRESS=1 make debug_test
          fi

      - name: Upload raw test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: raw-test-${{ matrix.type }}
          path: test/
