name: C/C++ CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: test
      run: sudo make test
    - name: dubug_test thread
      run: |
        make fclean
        sudo make debug_test
    - name: dubug_test address
      run: |
        make fclean
        sudo _ADDRESS=1 make debug_test