name: C/C++ CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [normal, thread, address]
    steps:
      - uses: actions/checkout@v4

      - name: Build & Run ${{ matrix.type }} test
        run: |
          make fclean
          if [ "${{ matrix.type }}" = "normal" ]; then
            sudo make test
            tar -cJf test.tar.xz test
          elif [ "${{ matrix.type }}" = "thread" ]; then
            sudo make debug_test
            tar -cJf test_thread.tar.xz test
          elif [ "${{ matrix.type }}" = "address" ]; then
            sudo _ADDRESS=1 make debug_test
            tar -cJf test_address.tar.xz test
          fi

      - name: Upload ${{ matrix.type }} logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.type }}
          path: test*.tar.xz

